### ISSUE TITLE
NPE for controller.initialize()

### ISSUE THREAD

**Issue by cmoulliard** [forge/springboot-addon#1]
When we launch maven test `mvn test`, we get a NPE at this line 

https://github.com/forge/springboot-addon/blob/master/src/test/java/org/jboss/forge/addon/springboot/SetupCommandTest.java#L54
```
	@Test
	public void checkCommandMetadata() throws Exception {
		try (CommandController controller = uiTestHarness.createCommandController(SpringBootNewProjectCommand.class, project.getRoot()) {
			controller.initialize(); // NPE reported here
```

- The temporary project is well created locally
- Log file is [available](https://gist.github.com/cmoulliard/2371af2fa5636a9a10580d9f9de8d242#file-gistfile1-txt-L434-L435)

**Comment by gastaldi** [comment]
You need to add SpringBootSetupFlow to https://github.com/forge/springboot-addon/blob/master/src/main/resources/META-INF/services/org.jboss.forge.furnace.container.simple.Service
