### ISSUE TITLE
Please set a `User-Agent` header for your requests on start.spring.io

### ISSUE THREAD

**Issue by snicoll** [forge/springboot-addon#3]
I poked quickly in the code and couldn't find any evidence of this so please forgive me if that's the case. We'd like that each Initializr client had a user-agent header for all traffic to start.spring.io

There are a few (concrete) examples in [`AgentTests`](https://github.com/spring-io/initializr/blob/master/initializr-generator/src/test/java/io/spring/initializr/util/AgentTests.java)

**Comment by cmoulliard** [comment]
@snicoll Do you agree that I set the agent as such `SpringBootForgeCli/1.0.0.Alpha` ?

**Comment by snicoll** [comment]
Whatever makes sense for you works for me. Thanks for the quick feedback!

**Comment by cmoulliard** [comment]
Released 1.0.0.Alpha3 including this fix
